export const sxCartHeader = {
  display: "flex",
  position: "fixed",
  top: 0,
  left: 0,
  width: "100%",
  maxWidth: "450px",
  height: "4.5rem",
  justifyContent: "space-between",
  alignItems: "center",
  padding: "1rem",
  zIndex: 100,
  backgroundColor: "white",
  boxShadow: "0 0 10px rgba(0, 0, 0, 0.1)",
};